name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Run tests with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew --stacktrace --info spotbugsMain

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: 'Spotbugs Reports'
          path: ./build/reports/
